#!/bin/bash

USAGE=$(cat <<-EOF

Usage:
  $(basename $0) [-e engine] [-n name] [-p [ip:]port] [-t t3-build] [-v volume] [--] [Docker/Podman option]...
  $(basename $0) -h

Runs the undecaf/typo3-dev TYPO3 container in Docker or Podman.

Although  all options are optional, at least one option must be set ('--' is sufficient)
as a precaution against inadvertent command invocation.

Options (default values can be overridden by environment variables):
  -e engine     Container engine to use: 'docker', 'podman' or an absolute path to the
                engine executable. 
                Default: TYPO3DEV_ENGINE, or 'podman' if installed, else 'docker'.
  -n name       Container or pod name to assign. Default: TYPO3DEV_NAME, or 'typo3'.
  -t t3-build   Tag of image to run, consisting of TYPO3 version and build version,
                e.g. '8.7-1.3' or '9.5-latest'.
                Default: TYPO3DEV_TAG, or 'latest', i.e. the latest build for the most
                recent TYPO3 version.
  -v typo3-vol  Volume name or absolute directory path to be mapped to the TYPO3 root 
                directory inside the container. Default: TYPO3DEV_ROOT, or 'typo3-vol'.
  -d db-type    Type of database container: 'm' for MariaDB, 'p' for PostgreSQL.
                If omitted, the SQLite instance in the TYPO3 container will be used.
  -w db-vol     Volume name or absolute directory path to be mapped to the database data
                directory inside the database container; requires -d.
                Defaults: TYPO3DEV_MARIADB, or 'typo3-mariadb' for MariaDB,
                TYPO3DEV_POSTGRESQL, or 'typo3-postgresql' for PostgreSQL.
  -h            Displays this text and exits.

Additional options for the Docker/Podman 'run' command can be added after the options
described above. If necessary, '--' can be used to separate the option groups.
   
EOF
)

OPT_COUNT=$#

. $(dirname $0)/_args.sh

[ $OPT_COUNT -eq 0 ] && usage 'No option set but at least one is required'

trap "{ set +x; } 2>/dev/null; echo $'\nContainer $NAME stopped'" SIGINT
set -x

$ENGINE run \
    --name $NAME \
    --hostname "typo3.$(hostname)" \
    --volume $T3_VOL:$TYPO3_ROOT \
    --publish 127.0.0.1:8080:80 \
    $REMOVE_OPT \
    $HOST_IP_OPT \
    $@ \
    $REPO_SLUG${TAG:+:$TAG}
