#!/bin/bash -x

podman run \
	--name typo3 \
	--hostname dev.typo3.local \
	--env TIMEZONE=Europe/Vienna \
	--env MODE=dev \
	--env php_short_open_tag=On \
	--env php_error_reporting=E_ALL \
	--env php_display_errors=On \
	--env php_html_errors=On \
	--env XDEBUG_ENABLED=true \
	--publish 127.0.0.1:8080:80 \
	localhost/typo3-composer
#	--detach \